name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  pie_chart: ^5.1.0
  flutter_spinkit: ^5.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue:
    path: ../

flutter:
  uses-material-design: true



  assets:
    - images/Transparent_Waze.png
    - images/virus.png